### ISSUE TITLE
gunicorn and gevent errors showing up in logs

### ISSUE THREAD

**Issue by ccostino** [fecgov/fec-eregs#400]
I'm seeing a smattering of the following stack traces in the logs related to `gunicorn` and `gevent`:

```
[2018-04-24 10:17:31 -0400] [66] [ERROR] Error handling request /preloader.swf
Traceback (most recent call last):
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gunicorn/workers/async.py", line 96, in handle_request
    listener_name, self.cfg)
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 201, in create
    path_info = path_info.split(script_name, 1)[1]
IndexError: list index out of range
```

I'm not sure where the breakdown is yet, but they are causing numerous alerts to get sent given the regularity with which they appear to be happening.

**Comment by ccostino** [comment]
Thanks for helping look into this, @cmc333333!  The issue appears to be with the [`SCRIPT_NAME` environment variable in the manifest file](https://github.com/fecgov/fec-eregs/blob/1902b0cbece63bbcc9b4774e54524c500d7345ba/manifest_prod.yml#L13), causing `gunicorn` to fail processing it (as [seen here in gunicorn the source code](https://github.com/benoitc/gunicorn/blob/19.7.1/gunicorn/http/wsgi.py#L125)).

It looks like we need a second argument/settings/parameter/something with the script name, not just `/regulations`.

**Comment by ccostino** [comment]
More details and a possible fix could be gleaned from here:  https://github.com/benoitc/gunicorn/issues/679

**Comment by ccostino** [comment]
False alarm!  This is a non-issue for us in the sense that these are requests for things that don't exist in the server (as noted in the example above).  It'd be nice if this was handled a bit more gracefully but I'm not sure how we can accomplish that since this is handling in `gunicorn` itself.

Closing this for now as there's nothing more for us to do at the moment.
