### ISSUE TITLE
unable to parse 2018 eregs on local.

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-eregs#426]
Tried to parse Title 11 FEC 2018 eregs on local. Out of 45 eregs only 7 parsed  successfully and rest of them failed with errors. Noticed two different type of errors in the logs.

**Here is the list of 7  eregs that parsed successfully:**
![screen shot 2018-12-14 at 2 52 55 pm](https://user-images.githubusercontent.com/11650355/50024741-5b3fc400-ffb1-11e8-8dec-eaa3366d1303.png)

regs with **single citations** failed with an  **IndexError: string index out of range error** error
regs with **multiple citations** failed with an **AttributeError: 'str' object has no attribute 'start'`** error.
 
**Example 1:**
**Parsing 11 CFR 9038 failed with an IndexError:**
2018-12-14 19:01:09 regparser.history.annual                 No <PARTS> in https://www.gpo.gov/fdsys/bulkdata/CFR/2018/title-11/CFR-2018-title11-vol1.xml. Assuming this volume contains all of the regs
2018-12-14 19:01:09 regparser.commands.annual_version        Getting annual version - 11 CFR 9038, Year: 2018
2018-12-14 19:01:10 regparser.tree.gpo_cfr.builder           Build tree <Element CFRGRANULE at 0x10c1cbf88>
2018-12-14 19:01:10 regparser.tree.gpo_cfr.builder           Preprocessing XML <Element CFRGRANULE at 0x10c1cbf88>
2018-12-14 19:01:10 regparser.content                        Could not load macros from regcontent.macros
Traceback (most recent call last):
  File "/Users/pkasireddy/.pyenv/versions/eregs365/bin/eregs", line 11, in <module>
    sys.exit(eregs())
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/web/management/runner.py", line 22, in eregs
    runner(args)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/web/management/runner.py", line 14, in runner
    execute_from_command_line(argv)
  File "/Users/
pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/djclick/adapter.py", line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/djclick/adapter.py", line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/retry.py", line 57, in run_or_resolve
    cmd()
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/pipeline.py", line 32, in pipeline
    ctx.invoke(annual_version, **params)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/annual_version.py", line 73, in annual_version
    process_if_needed(vol, cfr_part)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/annual_version.py", line 29, in process_if_needed
    tree = builder.build_tree(annual_entry.read().xml)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/builder.py", line 98, in build_tree
    plugin(tree, xml_node)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/section.py", line 258, in __call__
    sections = build_from_section(parent.cfr_part, xml_node)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/section.py", line 159, in build_from_section
    RegtextParagraphProcessor().process(section_xml, sect_node)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/xml_parser/paragraph_processor.py", line 122, in process
    nodes = self.parse_nodes(xml)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/xml_parser/paragraph_processor.py", line 48, in parse_nodes
    nodes.extend(tag_matcher.derive_nodes(child, processor=self))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/section.py", line 208, in derive_nodes
    for marker, plain_text, tagged_text in split_by_markers(xml):
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/section.py", line 188, in split_by_markers
    markers_list = get_markers(tagged_text, next_marker(xml))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/section.py", line 52, in get_markers
    collapsed = collapsed_markers(text)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/tree/gpo_cfr/section.py", line 101, in collapsed_markers
    potential = [trip for trip in remove_citation_overlaps(text, potential)]
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 302, in remove_citation_overlaps
    return [(m, start, end) for m, start, end in possible_markers
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 306, in <listcomp>
    for e in internal_citations(text))]
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 258, in internal_citations
    single(grammar.marker_paragraph, False)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 242, in single
    initial_label, comment))
  **`File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 201, in single_citations
    start = match.marker.pos[1]
IndexError: string index out of range`**

**Example #2** 
**Parsing 11 CFR 9039 regulation failed with a AttributeError:**
2018-12-14 19:01:12 regparser.history.annual                 No <PARTS> in https://www.gpo.gov/fdsys/bulkdata/CFR/2018/title-11/CFR-2018-title11-vol1.xml. Assuming this volume contains all of the regs
2018-12-14 19:01:12 regparser.commands.annual_version        Getting annual version - 11 CFR 9039, Year: 2018
2018-12-14 19:01:13 regparser.commands.layers                Build layers - 11 CFR 9039
Traceback (most recent call last):
  File "/Users/pkasireddy/.pyenv/versions/eregs365/bin/eregs", line 11, in <module>
    sys.exit(eregs())
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/web/management/runner.py", line 22, in eregs
    runner(args)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/web/management/runner.py", line 14, in runner
    execute_from_command_line(argv)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/djclick/adapter.py", line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/djclick/adapter.py", line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/retry.py", line 57, in run_or_resolve
    cmd()
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/pipeline.py", line 37, in pipeline
    ctx.invoke(layers, **params)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/layers.py", line 91, in layers
    process_cfr_layers(stale, tree_title, version_entry)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/commands/layers.py", line 64, in process_cfr_layers
    tree, cfr_title=int(cfr_title), version=version).build()
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/layer.py", line 52, in build
    self.builder(self.tree, cache)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/layer.py", line 48, in builder
    self.builder(c, cache)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/layer.py", line 48, in builder
    self.builder(c, cache)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/layer.py", line 43, in builder
    layer_element = self.process(node)
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/external_citations.py", line 13, in process
    for finder in external_types.ALL
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/external_citations.py", line 14, in <listcomp>
    for cite in finder().find(node)]
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/layer/external_types.py", line 47, in find
    for cit in cfr_citations(node.text):
  File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 319, in cfr_citations
    include_fill=include_fill))
  **`File "/Users/pkasireddy/.pyenv/versions/3.6.5/envs/eregs365/lib/python3.6/site-packages/regparser/citations.py", line 223, in multiple_citations
    match.pos.start, match.pos.end, new_label,
AttributeError: 'str' object has no attribute 'start'`**

**Comment by qqss88** [comment]
thx. I am testing the 'eregs pipeline' for title 11. I am taking it from here.

**Comment by fec-jli** [comment]
1) I setup regulations-parser docker on my local and run parser `pipeline` for all 45 parts ,no any issue, all passed. 
2)then I downgrade python version to 3.6.1 for `fec-eregs` repo, re-load all regulations to local db, all parsed successfully. 

so the key point is `POST`method part of python code in `fec-eregs` just supports max version python 3.6.1, The regulations-parser repo only supports `python 3.5` from their website info.[https://eregs-parser.readthedocs.io/en/latest/overview.html ](https://eregs-parser.readthedocs.io/en/latest/overview.html ) 

Thanks Charlie help me setup Docker.

**Comment by fec-jli** [comment]
We may need Modify runtime.txt set python version = 3.6.1
3.6.5 for GET method works well.

**Comment by qqss88** [comment]
thanks @fec-jli for testing the docker eregs-parser version on local api. I think we'll use the docker image and docker version of eregs parser for future eregs data injection in case the raw loading script fails due to python version/library version issue. I am adding the docker-based loading script for future reference. Check eregs parser documentation for details: https://eregs-parser.readthedocs.io/en/latest/

**Comment by patphongs** [comment]
If we use python version 3.5, we should be able to parse the eregs. @fec-jli has tested to confirm this. As a nice-to-have, we can work on using docker to have a consistent environment to parse eregs.

**Comment by fec-jli** [comment]
We can use python 3.5 -3.6.1 to parse regulation on local. close this issue now.
for docker version eregs-parser , reference issue [https://github.com/fecgov/fec-eregs/issues/430](https://github.com/fecgov/fec-eregs/issues/430)
