### ISSUE TITLE
[update python packages] figure out python packages to install to get eregs working

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-eregs#461]
### Summary
If we install @fec-jli 's results of `pip freeze` and try to load_regs, it works. But if we try from using the packages in `requirements.txt` and `requirements_dev.txt` it does not work. 

One simple fix would be to simply `pip freeze >> requirements.txt` and remove `requirements_dev.txt`, but it may be overkill, since auxiliary packages may exist. 

The superset of packages which allows a successful load_regs is:

This situation is a good use case for `pip-compile`

```
amqp==2.2.2
anyjson==0.3.3
appnope==0.1.0
asn1crypto==0.24.0
attrs==17.4.0
bandit==1.4.0
billiard==3.5.0.3
boto3==1.5.13
botocore==1.8.50
cached-property==1.3.1
celery==4.1.0
certifi==2018.1.18
cfenv==0.5.3
cffi==1.11.5
chardet==3.0.4
click==6.7
coloredlogs==9.0
cryptography==2.2.2
decorator==4.2.1
dj-database-url==0.4.2
Django==1.11.11
django-click==2.0.0
django-debug-toolbar==1.9.1
django-haystack==2.4.1
django-js-asset==1.0.0
django-mptt==0.8.7
django-overextends==0.4.3
django-rq==1.0.1
djangorestframework==3.7.7
docutils==0.14
elasticsearch==1.9.0
enum34==1.1.6
-e git+git@github.com:fecgov/fec-eregs.git@ca141fd5e431805df1a70ac76d91bd9a5ac4b976#egg=fec_regparser&subdirectory=eregs_extensions
furl==1.0.1
futures==3.1.1
gevent==1.2.2
gitdb2==2.0.3
GitPython==2.1.8
greenlet==0.4.13
gunicorn==19.7.1
humanfriendly==4.9
idna==2.6
inflection==0.3.1
invoke==0.22.0
ipdb==0.10.3
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.1
jmespath==0.9.3
json-delta==2.0
jsonschema==2.5.1
kombu==4.1.0
lxml==4.2.1
marshmallow==2.19.2
networkx==2.1
newrelic==2.100.0.84
orderedmultidict==0.7.11
parso==0.1.1
pbr==4.0.0
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psycopg2==2.7.3.2
ptyprocess==0.5.2
pycparser==2.18
pyelasticsearch==1.4
Pygments==2.2.0
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-constraint==1.3.1
python-dateutil==2.7.2
pytz==2018.3
PyYAML==3.12
redis==2.10.6
-e git+https://github.com/18F/regulations-core.git@d5443336b0ec287e62837614bf1e359465cc30fe#egg=regcore
-e git+https://github.com/18F/regulations-parser.git@e757cb74aea1b4c7c29293c749561510d4adba1e#egg=regparser
regulations==8.4.2
requests==2.21.0
requests-cache==0.4.13
requests-toolbelt==0.8.0
roman==2.0.0
rq==0.10.0
s3transfer==0.1.13
simplegeneric==0.8.1
simplejson==3.13.2
six==1.11.0
smmap2==2.0.3
sqlparse==0.2.4
stevedore==1.28.0
traitlets==4.3.2
urllib3==1.22
vine==1.1.4
wcwidth==0.1.7
webargs==5.4.0
whitenoise==3.3.1
```

### Completion criteria
- [ ] either figure out which packages of the above are necessary and sufficient or use that set
- [ ] steps all the way through load_regs are successful.

**Comment by jason-upchurch** [comment]
The first error thrown when running from install of current `requirements{,_dev}.txt` is:

```
(eregs-demo) feccs002:fec-eregs jupchurch$ python load_regs/load_fec_regs.py local
Traceback (most recent call last):
  File "/Users/jupchurch/.pyenv/versions/eregs-demo/bin/eregs", line 11, in <module>
    sys.exit(eregs())
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/web/management/runner.py", line 22, in eregs
    runner(args)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/web/management/runner.py", line 14, in runner
    execute_from_command_line(argv)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/djclick/adapter.py", line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/djclick/adapter.py", line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 57, in run_or_resolve
    cmd()
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 40, in get_command
    for command in sub_commands():
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 25, in sub_commands
    module = import_module('regparser.commands.{0}'.format(command_name))
  File "/Users/jupchurch/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/annual_editions.py", line 6, in <module>
    from regparser.history import annual
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/history/annual.py", line 12, in <module>
    from regparser.tree.xml_parser.xml_wrapper import XMLWrapper
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/tree/xml_parser/xml_wrapper.py", line 7, in <module>
    from regparser.tree.xml_parser.preprocessors import replace_html_entities
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/tree/xml_parser/preprocessors.py", line 17, in <module>
    from regparser.grammar.tokens import uncertain_label
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/grammar/tokens.py", line 58, in <module>
    class Context(Token):
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/grammar/tokens.py", line 65, in Context
    label = attr.attrib(convert=lambda label: [p or None for p in label])
TypeError: attrib() got an unexpected keyword argument 'convert'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/Users/jupchurch/.pyenv/versions/eregs-demo/bin/eregs", line 11, in <module>
    sys.exit(eregs())
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/web/management/runner.py", line 22, in eregs
    runner(args)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/web/management/runner.py", line 14, in runner
    execute_from_command_line(argv)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/djclick/adapter.py", line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/djclick/adapter.py", line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 57, in run_or_resolve
    cmd()
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 40, in get_command
    for command in sub_commands():
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/retry.py", line 25, in sub_commands
    module = import_module('regparser.commands.{0}'.format(command_name))
  File "/Users/jupchurch/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/commands/annual_editions.py", line 6, in <module>
    from regparser.history import annual
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/history/annual.py", line 12, in <module>
    from regparser.tree.xml_parser.xml_wrapper import XMLWrapper
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/tree/xml_parser/xml_wrapper.py", line 7, in <module>
    from regparser.tree.xml_parser.preprocessors import replace_html_entities
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/tree/xml_parser/preprocessors.py", line 17, in <module>
    from regparser.grammar.tokens import uncertain_label
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/grammar/tokens.py", line 58, in <module>
    class Context(Token):
  File "/Users/jupchurch/.pyenv/versions/3.6.1/envs/eregs-demo/lib/python3.6/site-packages/regparser/grammar/tokens.py", line 65, in Context
    label = attr.attrib(convert=lambda label: [p or None for p in label])
TypeError: attrib() got an unexpected keyword argument 'convert'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by pkfec** [comment]
@jason-upchurch I was getting the same exact error msg on my local when i try to load the regulations with the latest `requirement-*.txt` while i activated a new python virtualenv.

If i removed the `IPython` or downgraded `networkx` pkg to `networkx==1.11` , only 5 regulations parsed on my local.

**Comment by jason-upchurch** [comment]
> @jason-upchurch I was getting the same exact error msg on my local when i try to load the regulations with the latest `requirement-*.txt` while i activated a new python virtualenv.
> 
> If i removed the `IPython` or downgraded `networkx` pkg to `networkx==1.11` , only 5 regulations parsed on my local.

@pkfec can we pair on this? In addition to the new requirements, you may need to rebuild everything. The Parts that loaded for me were:
1, 2, 4, 5, 6, 7, 8, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 200, 201, 9001, 9002, 9003, 9004, 9005, 9006, 9007, 9008, 9012, 9031, 9032, 9033, 9034, 9035, 9036, 9037, 9038, 9039.

The example output I see:

```
  Apply all migrations: admin, auth, contenttypes, index, jobs, sessions
Running migrations:
  No migrations to apply.
2019-11-18 19:03:00 regparser.history.annual                 No <PARTS> in https://www.gpo.gov/fdsys/bulkdata/CFR/2019/title-11/CFR-2019-title11-vol1.xml. Assuming this volume contains all of the regs
2019-11-18 19:03:00 regparser.commands.annual_version        Getting annual version - 11 CFR 9039, Year: 2019
2019-11-18 19:03:01 regparser.commands.layers                Build layers - 11 CFR 9039
2019-11-18 19:03:06 regparser.commands.diffs                 Build diffs - 11 Part 9039
2019-11-18 19:03:07 regparser.commands.write_to              Export output - 11 CFR 9039, Destination: http://localhost:8000/api
```

**Comment by pkfec** [comment]
@jason-upchurch After your excellent  eregs requirements (magic) demo, i  replaced my local requirement  file w/ @fec-jli, and all regs parsed without any errors. I didnt realize that @fec-jli kept her old python vm while i worked on new python virtual environment everytime i had to parse the eregs.

**Comment by pkfec** [comment]
1. Forked regulations-core, regulations-site, regualtions-parser repos into fecgov github account 
2. Updated Django to LTS v2.2.11 on all 3 repos.
3. Updated python packages as needed and checked-in the changes on 3 repos.
4. While parsing regs on my local env, only 7 parsed successfully and remaining 38 failed shown in the stack trace below. @johnnyporkchops and I have the same exact issue on our local env's. (I had these parsing issues in 2018 see#426 )
5. @jason-upchurch is helping me with the package upgrades as his local eregs env seems OK. 
6. He is able to parse all 45 regs without django upgrades. Currently he is updating django to LTS v2.2.11 on each repo and testing the parser on this local.

Here is the parser error stack trace:
(jasonenv) macadmins-MacBook-Pro-5:fec-eregs pkasireddy$ python load_regs/load_fec_regs.py local
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, index, jobs, sessions
Running migrations:
  No migrations to apply.
2020-04-22 19:12:57 regparser.commands.annual_version        No annual edition for 11 CFR 1, Year: 2020. Trying 2019.
2020-04-22 19:12:57 regparser.history.annual                 No <PARTS> in https://www.gpo.gov/fdsys/bulkdata/CFR/2019/title-11/CFR-2019-title11-vol1.xml. Assuming this volume contains all of the regs
2020-04-22 19:12:57 regparser.commands.annual_version        Getting annual version - 11 CFR 1, Year: 2019
2020-04-22 19:12:58 regparser.tree.gpo_cfr.builder           Build tree <Element CFRGRANULE at 0x10b883460>
2020-04-22 19:12:58 regparser.tree.gpo_cfr.builder           Preprocessing XML <Element CFRGRANULE at 0x10b883460>
2020-04-22 19:12:58 regparser.content                        Could not load macros from regcontent.macros
Traceback (most recent call last):
  File “/Users/pkasireddy/.pyenv/versions/jasonenv/bin/eregs”, line 10, in <module>
    sys.exit(eregs())
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/web/management/runner.py”, line 22, in eregs
    runner(args)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/web/management/runner.py”, line 14, in runner
    execute_from_command_line(argv)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/django/core/management/_init_.py”, line 364, in execute_from_command_line
    utility.execute()
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/django/core/management/_init_.py”, line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/djclick/adapter.py”, line 62, in run_from_argv
    return self.main(args=argv[2:], standalone_mode=False)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 717, in main
    rv = self.invoke(ctx)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/djclick/adapter.py”, line 49, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/retry.py”, line 47, in invoke
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/retry.py”, line 57, in run_or_resolve
    cmd()
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/retry.py”, line 47, in <lambda>
    lambda: super(RetryingCommand, self).invoke(deepcopy(ctx)))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 555, in invoke
    return callback(*args, **kwargs)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/decorators.py”, line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/pipeline.py”, line 32, in pipeline
    ctx.invoke(annual_version, **params)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/click/core.py”, line 555, in invoke
    return callback(*args, **kwargs)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/annual_version.py”, line 73, in annual_version
    process_if_needed(vol, cfr_part)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/commands/annual_version.py”, line 29, in process_if_needed
    tree = builder.build_tree(annual_entry.read().xml)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/builder.py”, line 98, in build_tree
    plugin(tree, xml_node)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 258, in _call_
    sections = build_from_section(parent.cfr_part, xml_node)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 159, in build_from_section
    RegtextParagraphProcessor().process(section_xml, sect_node)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/xml_parser/paragraph_processor.py”, line 122, in process
    nodes = self.parse_nodes(xml)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/xml_parser/paragraph_processor.py”, line 48, in parse_nodes
    nodes.extend(tag_matcher.derive_nodes(child, processor=self))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 208, in derive_nodes
    for marker, plain_text, tagged_text in split_by_markers(xml):
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 188, in split_by_markers
    markers_list = get_markers(tagged_text, next_marker(xml))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 52, in get_markers
    collapsed = collapsed_markers(text)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/tree/gpo_cfr/section.py”, line 101, in collapsed_markers
    potential = [trip for trip in remove_citation_overlaps(text, potential)]
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 302, in remove_citation_overlaps
    return [(m, start, end) for m, start, end in possible_markers
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 306, in <listcomp>
    for e in internal_citations(text))]
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 250, in internal_citations
    multiple(grammar.multiple_non_comments, False)
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 246, in multiple
    initial_label, comment))
  File “/Users/pkasireddy/.pyenv/versions/3.7.5/envs/jasonenv/lib/python3.7/site-packages/regparser/citations.py”, line 223, in multiple_citations
    match.pos.start, match.pos.end, new_label,
AttributeError: ‘str’ object has no attribute ‘start’

**Comment by lbeaufort** [comment]
Per @jason-upchurch "We have a sufficient  set rather than a necessary set of  requirements in requirements-parsing.txt."

**Comment by jason-upchurch** [comment]
thanks @lbeaufort, thank you for restating this! Per the completion criteria from Nov 2019: "either figure out which packages of the above are necessary and sufficient or use that set"

**Comment by jason-upchurch** [comment]
Created issue #513 to address future plans for `fec-eregs` which could inform prioritization of eregs work. The parsing function works as is, and it would be nice to optimize this functionality, but better to figure out our plans before investing cc @PaulClark2 @AmyKort

**Comment by pkfec** [comment]
Eeregs and parser are now running on python v3.7.12 after upgrading Django and Python in PR https://github.com/fecgov/fec-eregs/pull/647.
