### ISSUE TITLE
Fix failing build

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-eregs#468]
The `develop` build is failing https://circleci.com/gh/fecgov/fec-eregs/243

```
Traceback (most recent call last):
  File "/home/circleci/repo/.env/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/invoke/program.py", line 282, in run
    self.parse_collection()
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/invoke/program.py", line 356, in parse_collection
    self.load_collection()
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/invoke/program.py", line 508, in load_collection
    module, parent = loader.load(coll_name)
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/invoke/loader.py", line 69, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/local/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/circleci/repo/tasks.py", line 4, in <module>
    import git
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/circleci/repo/.env/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'

Exited with code exit status 1
```

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by lbeaufort** [comment]
@Harmon758 I just got there! Thanks so much! We will update to `GitPython==2.1.15`

**Comment by Harmon758** [comment]
You should be able to update to v3 as well, if Python 2 support isn't needed.

**Comment by lbeaufort** [comment]
For posterity, I'm only going to move up to the newest minor version, pending https://github.com/fecgov/fec-eregs/issues/450
