### ISSUE TITLE
Research upgrading to Django 2.2 LTS version

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-eregs#628]
Last time it was attempted to upgrade from Django 1 to Django 2, stylesheets were not loading and `grunt` was not working. Parsing was working.

Need to consider these packages when upgrading: `regulations-site`, `regulations-parser`, `regulations-core`

- [ ] Django is updated to Version 2.2 with all functionality working

Related issue #626

**Comment by pkfec** [comment]
`python manage.py migrate` errors:

(20211018-eregs-env) macadmins-mbp-5:fec-eregs pkasireddy$ python manage.py migrate
System check identified some issues:

WARNINGS:
regcore.Diff: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
regcore.Layer: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
regcore.NoticeCFRPart: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Operations to perform:
  Apply all migrations: auth, contenttypes, regcore, regulations, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying regcore.0001_initial... OK
  Applying regcore.0002_mptt_add_fields... OK
  Applying regcore.0003_mptt_copy_children...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/pkasireddy/.pyenv/versions/3.7.10/envs/20211018-eregs-env/src/regcore/regcore/migrations/0003_mptt_copy_children.py", line 17, in rebuild
    mptt.register(Regulation)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/mptt/__init__.py", line 13, in register
    return MPTTModelBase.register(*args, **kwargs)
  File "/Users/pkasireddy/.pyenv/versions/20211018-eregs-env/lib/python3.7/site-packages/mptt/models.py", line 352, in register
```
    cls._meta.index_together += (index_together,)
TypeError: unsupported operand type(s) for +=: 'set' and 'tuple'
```

**Comment by pkfec** [comment]
To resolve the ```TypeError: unsupported operand type(s) for +=: 'set' and 'tuple'```, @johnnyporkchops had to add external code to convert a set into a tuple in his local file system: `site-packages/mptt/models.py`

**Comment by pkfec** [comment]
Instead of monkey patching django-mptt, removed `alterindextogether` and `alteruniquetogether` regcore/migrations that instantly fixed the `TypeError: unsupported operand type(s) for +=: 'set' and 'tuple'`

code changes here#
https://github.com/fecgov/regulations-core/commit/4465793dd74f7707329dc78c79170ffa5d204fd1

**Comment by johnnyporkchops** [comment]
CF  logs show that ,with the above fix, all migrations are applied without error, but  gives Warning:
```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
`cf logs eregs` ouput on dev:
<img width="949" alt="Screen Shot 2021-11-17 at 1 43 32 AM" src="https://user-images.githubusercontent.com/5572856/142298223-668ad177-66c4-48f7-bedf-13a9cfc80d4b.png">


Creating a new migration(0016) by running `makemigrations` breaks the Circle build when deployed with `relation exists` error...
But tests  on dev have shown that instead, just editing `migration 0011` to add this operation  under the commented code, then rebuilding the app passes Circle build and removes the warning
Around line 44, under commented out `alterIndexTogethor`, add:
```
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('doc_type', 'version', 'label_string')},
        ),
         migrations.AlterIndexTogether(
             name='document',
             index_together={('doc_type', 'version', 'label_string')},
         ),
```

**Comment by pkfec** [comment]
Here is the [eregs-django 2.2.24 WIP pr](https://github.com/fecgov/fec-eregs/pull/631/files)

**Comment by pkfec** [comment]
The django upgrade implementation can be tracked here #632. Closing the research ticket.
